sudo: required

language: generic

services:
  - docker

before_install:
  - sudo apt-get update

install:
  - sudo apt-get upgrade docker-engine
  - docker pull debian:stable-slim

script:
  - docker build --compress --squash -t sinoru/swiftenv .
  - docker ps -a

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag sinoru/swiftenv sinoru/swiftenv:latest
    docker push sinoru/swiftenv;
    fi